[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
addopts = -v --tb=short --cov --cov-fail-under=90 --cov-config=pyproject.toml --color=no
markers =
    asyncio: mark a test as an async test.
asyncio_mode = auto