"""create flows and tasks tables

Revision ID: 91b3f4ede6ab
Revises: 
Create Date: 2026-03-12 23:11:44.844371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b3f4ede6ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flows',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plugin', sa.String(length=255), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=True, comment='List of task UUIDs'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('tasks',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('flow_uuid', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False, comment='pending, running, completed, failed'),
    sa.Column('timeout', sa.Float(), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True, comment='OpenAI format messages'),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['flow_uuid'], ['flows.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index('idx_task_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_task_flow_uuid', 'tasks', ['flow_uuid'], unique=False)
    op.create_index('idx_task_state', 'tasks', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_state', table_name='tasks')
    op.drop_index('idx_task_flow_uuid', table_name='tasks')
    op.drop_index('idx_task_created_at', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('flows')
    # ### end Alembic commands ###
