"""add status and flow_template to flows

Revision ID: 99b2044634b6
Revises: 91b3f4ede6ab
Create Date: 2026-03-14 16:58:38.394817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99b2044634b6"
down_revision: Union[str, None] = "91b3f4ede6ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "flows",
        sa.Column(
            "status", sa.String(length=20), nullable=False, server_default="created"
        ),
    )
    op.add_column(
        "flows", sa.Column("flow_template", sa.String(length=255), nullable=True)
    )
    op.create_index(op.f("ix_flows_status"), "flows", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flows_status"), table_name="flows")
    op.drop_column("flows", "flow_template")
    op.drop_column("flows", "status")
    # ### end Alembic commands ###
